title: Xing Yang's Homepage
page-top-title: Xing Yang
top-section-bg-text: Artificial Intelligence
home-subtitle: Xing Yang&ensp;|&ensp;杨星
copyright-text: '&copy; Xing Yang 2025-2027. All Rights Reserved.'
